Repository nim-works/nimskull, pull requests merged in 2024-12, with the labels that each got.

#1474 ci: update x86 macOS to version 13
  .github/workflows/ci.yml
Labels: ci

#1475 ci: split into smaller workflows with some improvements
  .github/workflows/build-and-test.yml
  .github/workflows/ci.yml
  .github/workflows/package.yml
  doc/ci.rst
Labels: ci

#1478 fix memory corruption when using standalone heap
  lib/system/osalloc.nim
  tests/system/tosalloc_standalone_heap.nim
Labels: bug

#1480 Revert "build(deps): Bump softprops/action-gh-release from 2.1.0 to 2.2.0"
  .github/workflows/publisher.yml
Labels: dependencies

#1482 cgirgen: remove the `var` expression fixup
  compiler/backend/cgirgen.nim
  compiler/backend/cgmeth.nim
  compiler/sem/liftdestructors.nim
  compiler/sem/semexprs.nim
Labels: compiler/backend, simplification
