Repository nim-works/nimskull, pull requests merged in 2025-01, with the labels that each got.

#1486 ci: install `libpcre3` for leak job
  .github/workflows/leak.yml
Labels: ci

#1485 fix(sem): crash with erroneous `is` expression
  compiler/sem/sem.nim
  compiler/sem/semexprs.nim
  tests/error_propagation/tin_expression_in_when.nim
Labels: bug, compiler/sem

#1487 ci: add Linux arm64 builds
  .github/workflows/ci.yml
Labels: enhancement, ci

#1489 ci: bump ubuntu image to 22.04
  .github/workflows/ci.yml
Labels: ci
